# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-20.04
  
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: Bash@3
  displayName: 'Veracode SCA scan'
  inputs:
    targetType: 'inline'
    script: |
     export SRCCLR_API_TOKEN="$(apiToken)"
     export SRCCLR_SCM_TYPE="GITHUB"
     export SRCCLR_SCM_TOKEN="$(scmToken)"
     curl -sSL https://download.sourceclear.com/ci.sh | bash -s -- scan --ws 3OOuvgA --pull-request | tee SCA_Results.txt

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/SCA_Results.txt
    artifactName: SCA-scan-results
