# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest
#  vmImage: "vs2017-win2016"
#  vmImage: windows-latest
  
steps:
#- task: Maven@3
#  inputs:
#    mavenPomFile: 'pom.xml'
#    mavenOptions: '-Xmx3072m'
#    javaHomeOption: 'JDKVersion'
#    jdkVersionOption: '1.8'
#    jdkArchitectureOption: 'x64'
#    publishJUnitResults: true
#    testResultsFiles: '**/surefire-reports/TEST-*.xml'
#    goals: 'package'

#- task: PowerShell@2
#  displayName: 'Veracode SCA scan'
#  env: {SRCCLR_API_TOKEN: $(apiToken)}
#  inputs:
#   targetType: 'inline'
#   script: |
#    Set-ExecutionPolicy AllSigned -Scope Process -Force
#    $ProgressPreference = "SilentlyContinue"
#    iex ((New-Object System.Net.WebClient).DownloadString('https://download.sourceclear.com/ci.ps1'))
#    srcclr scan --ws 3OOuvgA $(Build.SourcesDirectory) --update-advisor
- task: Bash@3
  displayName: 'Veracode SCA scan'
  inputs:
     targetType: 'inline'
     script: |
          export SRCCLR_API_TOKEN="$(apiToken)"
          curl -sSL https://download.sourceclear.com/ci.sh | bash -s -- scan --ws 3OOuvgA | tee SCA_Results.txt

