name: SCA scan via published Veracode Dependency Scanning action

on: 
  #schedule:
  #  - cron: 15 14 * * 6
    
  workflow_dispatch:

jobs:
  veracode-sca-task:
    runs-on: ubuntu-latest
    name: Scan remote repository for Issues

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: 
          veracode/veracode-sca@v1.09
        with:
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          #create-issues: true
          #quick: true
          #allow-dirty: false
          #recursive: true
          #fail-on-cvss: 1
          #min-cvss-for-issue: 1
          debug: false
