name: Veracode SCA agent scan

on:
  workflow_dispatch:

jobs:

  SCA_Scan:
    runs-on: ubuntu-latest

    steps:
      # Check out repository under $GITHUB_WORKSPACE, so job can access it
      - name: Check out repo 
        uses: actions/checkout@v2.5.0

      # run agent scan on the project
      - name: SCA Scan
        env: 
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: curl -sSL https://download.sourceclear.com/ci.sh | sh -s scan --ws 3OOuvgA | tee SCA_Results.txt
      - uses: actions/upload-artifact@v1
        with:
          name: SCAScanResults
          path: SCA_Results.txt  
